export { default as ClinicProfilePage } from './ClinicProfilePage'
export { default as OperatingHoursPage } from './OperatingHoursPage'
export { default as NotificationsPage  } from './NotificationsPage'
export { default as PaymentPage        } from './PaymentPage'
export { default as IntegrationsPage   } from './IntegrationsPage'
export { default as PreferencesPage    } from './PreferencesPage'
export { default as SystemSettingsPage } from './SystemSettingsPage'
